### ISSUE TITLE
iot_data_alloc_from_string can fail for large integers

### ISSUE THREAD

**Issue by iain-anderson** [IOTechSystems/iotech-c-utils#126]
iot_data_alloc_from_string (IOT_DATA_UINT64, "18446744073709551610")

gives a ui64 with value 9223372036854775807

this is due to using atoll() - need strtoull or sscanf instead

**Comment by SteveOss** [comment]
Show check xrt/iot/thrift repos for other uses of atoll. Should also add some iot_data_alloc_from_string
unit tests using defined integer max/min values to check results are correct.
